### ISSUE TITLE
Teleport to report location cords are innacurate.

### ISSUE THREAD

**Issue by sid-engel** [ZeppelinForDays/ReportPlus#3]
It seems that whenever a report is made, and I attempt to teleport to the location in which it was made, I am sent to a different set of cordinates.

Thank you for all the help, and support developing this plugin.

**Comment by ZeppelinForDays** [comment]
May I ask if you are teleporting between worlds? For example creating a report in "world1" and teleporting from "world2"? I believe this could possibly be your problem and I will work on it. Let me know otherwise. Also thank you for your response.

I added the support to teleport between worlds because I thought I would need it anyways and I assume that's the solution to your problem.

**Comment by sid-engel** [comment]
From what I know the testing had been conducted in the same world. I'll do additional testing and let you know.

**Comment by sid-engel** [comment]
Per testing with the latest update you've made, it looks like this issue is Resolved. Closing this out.
